#!/bin/sh

if grep -qx $GROUPE /etc/group
then
    groupadd kevoree
fi


if id -u kevoree >/dev/null 2>&1;
then
else useradd -g kevoree -d /usr/share/kevoree kevoree
fi

if [ -d "/usr/share/kevoree" ]
then
else mkdir /usr/share/kevoree
fi
touch /var/run/kevoree.pid

sudo chgrp kevoree /usr/share/kevoree kevoree
sudo chgrp kevoree /var/run/kevoree.pid

sudo update-rc.d kevoree defaults
