#!/bin/sh

if [ -z "$(getent group kevoree)" ];
then groupadd kevoree
fi

if [ -z "$(getent passwd kevoree)" ];
then useradd -g kevoree -d /usr/share/kevoree kevoree
else echo 'kevoree user already exists'
fi

if [ -d "/usr/share/kevoree" ];
then echo '/usr/share/kevoree verified'
else mkdir /usr/share/kevoree
fi

touch /var/run/kevoree.pid

chgrp kevoree /usr/share/kevoree
chgrp kevoree /var/run/kevoree.pid

